import { drizzleZeroConfig } from "drizzle-zero";

import * as drizzleSchema from "./src/schema";

export default drizzleZeroConfig(drizzleSchema, {
  tables: {
    lists: {
      id: true,
      householdId: true,
      name: true,
      normalizedName: true,
      sortKey: true,
      deletedAt: true,
      createdAt: true,
      updatedAt: true,
    },
    listItems: {
      id: true,
      householdId: true,
      listId: true,
      name: true,
      normalizedName: true,
      status: true,
      sortKey: true,
      createdAt: true,
      updatedAt: true,
    },
    households: {
      id: true,
      name: true,
      createdAt: true,
      updatedAt: true,
    },
    householdMembers: {
      id: true,
      householdId: true,
      userId: true,
      role: true,
      sortKey: true,
      createdAt: true,
      updatedAt: true,
    },
    householdModuleSettings: {
      householdId: true,
      moduleKey: true,
      enabled: true,
      createdAt: true,
      updatedAt: true,
    },
    recipes: {
      id: true,
      householdId: true,
      title: true,
      description: true,
      sortKey: true,
      deletedAt: true,
      createdAt: true,
      updatedAt: true,
    },
    recipeIngredients: {
      id: true,
      householdId: true,
      recipeId: true,
      name: true,
      amount: true,
      note: true,
      position: true,
      createdAt: true,
      updatedAt: true,
    },
    recipeCookLogs: {
      id: true,
      householdId: true,
      recipeId: true,
      cookedAt: true,
      comment: true,
      createdAt: true,
      updatedAt: true,
    },
    recipeImages: {
      id: true,
      householdId: true,
      recipeId: true,
      cookLogId: true,
      contentType: true,
      byteSize: true,
      position: true,
      confirmedAt: true,
      width: true,
      height: true,
      createdAt: true,
      updatedAt: true,
    },
  },
});
