/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated.index'
import { Route as AuthenticatedHouseholdsHouseholdIdRouteImport } from './routes/_authenticated.households.$householdId'
import { Route as AuthenticatedHouseholdsHouseholdIdIndexRouteImport } from './routes/_authenticated.households.$householdId.index'
import { Route as AuthenticatedHouseholdsHouseholdIdListsRouteImport } from './routes/_authenticated.households.$householdId.lists'
import { Route as AuthenticatedHouseholdsHouseholdIdRecipesRouteImport } from './routes/_authenticated.households.$householdId.recipes'
import { Route as AuthenticatedHouseholdsHouseholdIdSettingsRouteImport } from './routes/_authenticated.households.$householdId.settings'
import { Route as AuthenticatedHouseholdsHouseholdIdListsIndexRouteImport } from './routes/_authenticated.households.$householdId.lists.index'
import { Route as AuthenticatedHouseholdsHouseholdIdListsListIdRouteImport } from './routes/_authenticated.households.$householdId.lists.$listId'
import { Route as AuthenticatedHouseholdsHouseholdIdRecipesIndexRouteImport } from './routes/_authenticated.households.$householdId.recipes.index'
import { Route as AuthenticatedHouseholdsHouseholdIdRecipesRecipeIdRouteImport } from './routes/_authenticated.households.$householdId.recipes.$recipeId'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHouseholdsHouseholdIdRoute =
  AuthenticatedHouseholdsHouseholdIdRouteImport.update({
    id: '/households/$householdId',
    path: '/households/$householdId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedHouseholdsHouseholdIdIndexRoute =
  AuthenticatedHouseholdsHouseholdIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedHouseholdsHouseholdIdRoute,
  } as any)
const AuthenticatedHouseholdsHouseholdIdListsRoute =
  AuthenticatedHouseholdsHouseholdIdListsRouteImport.update({
    id: '/lists',
    path: '/lists',
    getParentRoute: () => AuthenticatedHouseholdsHouseholdIdRoute,
  } as any)
const AuthenticatedHouseholdsHouseholdIdRecipesRoute =
  AuthenticatedHouseholdsHouseholdIdRecipesRouteImport.update({
    id: '/recipes',
    path: '/recipes',
    getParentRoute: () => AuthenticatedHouseholdsHouseholdIdRoute,
  } as any)
const AuthenticatedHouseholdsHouseholdIdSettingsRoute =
  AuthenticatedHouseholdsHouseholdIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedHouseholdsHouseholdIdRoute,
  } as any)
const AuthenticatedHouseholdsHouseholdIdListsIndexRoute =
  AuthenticatedHouseholdsHouseholdIdListsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedHouseholdsHouseholdIdListsRoute,
  } as any)
const AuthenticatedHouseholdsHouseholdIdListsListIdRoute =
  AuthenticatedHouseholdsHouseholdIdListsListIdRouteImport.update({
    id: '/$listId',
    path: '/$listId',
    getParentRoute: () => AuthenticatedHouseholdsHouseholdIdListsRoute,
  } as any)
const AuthenticatedHouseholdsHouseholdIdRecipesIndexRoute =
  AuthenticatedHouseholdsHouseholdIdRecipesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedHouseholdsHouseholdIdRecipesRoute,
  } as any)
const AuthenticatedHouseholdsHouseholdIdRecipesRecipeIdRoute =
  AuthenticatedHouseholdsHouseholdIdRecipesRecipeIdRouteImport.update({
    id: '/$recipeId',
    path: '/$recipeId',
    getParentRoute: () => AuthenticatedHouseholdsHouseholdIdRecipesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/households/$householdId': typeof AuthenticatedHouseholdsHouseholdIdRouteWithChildren
  '/households/$householdId/lists': typeof AuthenticatedHouseholdsHouseholdIdListsRouteWithChildren
  '/households/$householdId/recipes': typeof AuthenticatedHouseholdsHouseholdIdRecipesRouteWithChildren
  '/households/$householdId/settings': typeof AuthenticatedHouseholdsHouseholdIdSettingsRoute
  '/households/$householdId/': typeof AuthenticatedHouseholdsHouseholdIdIndexRoute
  '/households/$householdId/lists/$listId': typeof AuthenticatedHouseholdsHouseholdIdListsListIdRoute
  '/households/$householdId/recipes/$recipeId': typeof AuthenticatedHouseholdsHouseholdIdRecipesRecipeIdRoute
  '/households/$householdId/lists/': typeof AuthenticatedHouseholdsHouseholdIdListsIndexRoute
  '/households/$householdId/recipes/': typeof AuthenticatedHouseholdsHouseholdIdRecipesIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/': typeof AuthenticatedIndexRoute
  '/households/$householdId/settings': typeof AuthenticatedHouseholdsHouseholdIdSettingsRoute
  '/households/$householdId': typeof AuthenticatedHouseholdsHouseholdIdIndexRoute
  '/households/$householdId/lists/$listId': typeof AuthenticatedHouseholdsHouseholdIdListsListIdRoute
  '/households/$householdId/recipes/$recipeId': typeof AuthenticatedHouseholdsHouseholdIdRecipesRecipeIdRoute
  '/households/$householdId/lists': typeof AuthenticatedHouseholdsHouseholdIdListsIndexRoute
  '/households/$householdId/recipes': typeof AuthenticatedHouseholdsHouseholdIdRecipesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/households/$householdId': typeof AuthenticatedHouseholdsHouseholdIdRouteWithChildren
  '/_authenticated/households/$householdId/lists': typeof AuthenticatedHouseholdsHouseholdIdListsRouteWithChildren
  '/_authenticated/households/$householdId/recipes': typeof AuthenticatedHouseholdsHouseholdIdRecipesRouteWithChildren
  '/_authenticated/households/$householdId/settings': typeof AuthenticatedHouseholdsHouseholdIdSettingsRoute
  '/_authenticated/households/$householdId/': typeof AuthenticatedHouseholdsHouseholdIdIndexRoute
  '/_authenticated/households/$householdId/lists/$listId': typeof AuthenticatedHouseholdsHouseholdIdListsListIdRoute
  '/_authenticated/households/$householdId/recipes/$recipeId': typeof AuthenticatedHouseholdsHouseholdIdRecipesRecipeIdRoute
  '/_authenticated/households/$householdId/lists/': typeof AuthenticatedHouseholdsHouseholdIdListsIndexRoute
  '/_authenticated/households/$householdId/recipes/': typeof AuthenticatedHouseholdsHouseholdIdRecipesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/households/$householdId'
    | '/households/$householdId/lists'
    | '/households/$householdId/recipes'
    | '/households/$householdId/settings'
    | '/households/$householdId/'
    | '/households/$householdId/lists/$listId'
    | '/households/$householdId/recipes/$recipeId'
    | '/households/$householdId/lists/'
    | '/households/$householdId/recipes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/signup'
    | '/'
    | '/households/$householdId/settings'
    | '/households/$householdId'
    | '/households/$householdId/lists/$listId'
    | '/households/$householdId/recipes/$recipeId'
    | '/households/$householdId/lists'
    | '/households/$householdId/recipes'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/_authenticated/'
    | '/_authenticated/households/$householdId'
    | '/_authenticated/households/$householdId/lists'
    | '/_authenticated/households/$householdId/recipes'
    | '/_authenticated/households/$householdId/settings'
    | '/_authenticated/households/$householdId/'
    | '/_authenticated/households/$householdId/lists/$listId'
    | '/_authenticated/households/$householdId/recipes/$recipeId'
    | '/_authenticated/households/$householdId/lists/'
    | '/_authenticated/households/$householdId/recipes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/households/$householdId': {
      id: '/_authenticated/households/$householdId'
      path: '/households/$householdId'
      fullPath: '/households/$householdId'
      preLoaderRoute: typeof AuthenticatedHouseholdsHouseholdIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/households/$householdId/': {
      id: '/_authenticated/households/$householdId/'
      path: '/'
      fullPath: '/households/$householdId/'
      preLoaderRoute: typeof AuthenticatedHouseholdsHouseholdIdIndexRouteImport
      parentRoute: typeof AuthenticatedHouseholdsHouseholdIdRoute
    }
    '/_authenticated/households/$householdId/lists': {
      id: '/_authenticated/households/$householdId/lists'
      path: '/lists'
      fullPath: '/households/$householdId/lists'
      preLoaderRoute: typeof AuthenticatedHouseholdsHouseholdIdListsRouteImport
      parentRoute: typeof AuthenticatedHouseholdsHouseholdIdRoute
    }
    '/_authenticated/households/$householdId/recipes': {
      id: '/_authenticated/households/$householdId/recipes'
      path: '/recipes'
      fullPath: '/households/$householdId/recipes'
      preLoaderRoute: typeof AuthenticatedHouseholdsHouseholdIdRecipesRouteImport
      parentRoute: typeof AuthenticatedHouseholdsHouseholdIdRoute
    }
    '/_authenticated/households/$householdId/settings': {
      id: '/_authenticated/households/$householdId/settings'
      path: '/settings'
      fullPath: '/households/$householdId/settings'
      preLoaderRoute: typeof AuthenticatedHouseholdsHouseholdIdSettingsRouteImport
      parentRoute: typeof AuthenticatedHouseholdsHouseholdIdRoute
    }
    '/_authenticated/households/$householdId/lists/': {
      id: '/_authenticated/households/$householdId/lists/'
      path: '/'
      fullPath: '/households/$householdId/lists/'
      preLoaderRoute: typeof AuthenticatedHouseholdsHouseholdIdListsIndexRouteImport
      parentRoute: typeof AuthenticatedHouseholdsHouseholdIdListsRoute
    }
    '/_authenticated/households/$householdId/lists/$listId': {
      id: '/_authenticated/households/$householdId/lists/$listId'
      path: '/$listId'
      fullPath: '/households/$householdId/lists/$listId'
      preLoaderRoute: typeof AuthenticatedHouseholdsHouseholdIdListsListIdRouteImport
      parentRoute: typeof AuthenticatedHouseholdsHouseholdIdListsRoute
    }
    '/_authenticated/households/$householdId/recipes/': {
      id: '/_authenticated/households/$householdId/recipes/'
      path: '/'
      fullPath: '/households/$householdId/recipes/'
      preLoaderRoute: typeof AuthenticatedHouseholdsHouseholdIdRecipesIndexRouteImport
      parentRoute: typeof AuthenticatedHouseholdsHouseholdIdRecipesRoute
    }
    '/_authenticated/households/$householdId/recipes/$recipeId': {
      id: '/_authenticated/households/$householdId/recipes/$recipeId'
      path: '/$recipeId'
      fullPath: '/households/$householdId/recipes/$recipeId'
      preLoaderRoute: typeof AuthenticatedHouseholdsHouseholdIdRecipesRecipeIdRouteImport
      parentRoute: typeof AuthenticatedHouseholdsHouseholdIdRecipesRoute
    }
  }
}

interface AuthenticatedHouseholdsHouseholdIdListsRouteChildren {
  AuthenticatedHouseholdsHouseholdIdListsListIdRoute: typeof AuthenticatedHouseholdsHouseholdIdListsListIdRoute
  AuthenticatedHouseholdsHouseholdIdListsIndexRoute: typeof AuthenticatedHouseholdsHouseholdIdListsIndexRoute
}

const AuthenticatedHouseholdsHouseholdIdListsRouteChildren: AuthenticatedHouseholdsHouseholdIdListsRouteChildren =
  {
    AuthenticatedHouseholdsHouseholdIdListsListIdRoute:
      AuthenticatedHouseholdsHouseholdIdListsListIdRoute,
    AuthenticatedHouseholdsHouseholdIdListsIndexRoute:
      AuthenticatedHouseholdsHouseholdIdListsIndexRoute,
  }

const AuthenticatedHouseholdsHouseholdIdListsRouteWithChildren =
  AuthenticatedHouseholdsHouseholdIdListsRoute._addFileChildren(
    AuthenticatedHouseholdsHouseholdIdListsRouteChildren,
  )

interface AuthenticatedHouseholdsHouseholdIdRecipesRouteChildren {
  AuthenticatedHouseholdsHouseholdIdRecipesRecipeIdRoute: typeof AuthenticatedHouseholdsHouseholdIdRecipesRecipeIdRoute
  AuthenticatedHouseholdsHouseholdIdRecipesIndexRoute: typeof AuthenticatedHouseholdsHouseholdIdRecipesIndexRoute
}

const AuthenticatedHouseholdsHouseholdIdRecipesRouteChildren: AuthenticatedHouseholdsHouseholdIdRecipesRouteChildren =
  {
    AuthenticatedHouseholdsHouseholdIdRecipesRecipeIdRoute:
      AuthenticatedHouseholdsHouseholdIdRecipesRecipeIdRoute,
    AuthenticatedHouseholdsHouseholdIdRecipesIndexRoute:
      AuthenticatedHouseholdsHouseholdIdRecipesIndexRoute,
  }

const AuthenticatedHouseholdsHouseholdIdRecipesRouteWithChildren =
  AuthenticatedHouseholdsHouseholdIdRecipesRoute._addFileChildren(
    AuthenticatedHouseholdsHouseholdIdRecipesRouteChildren,
  )

interface AuthenticatedHouseholdsHouseholdIdRouteChildren {
  AuthenticatedHouseholdsHouseholdIdListsRoute: typeof AuthenticatedHouseholdsHouseholdIdListsRouteWithChildren
  AuthenticatedHouseholdsHouseholdIdRecipesRoute: typeof AuthenticatedHouseholdsHouseholdIdRecipesRouteWithChildren
  AuthenticatedHouseholdsHouseholdIdSettingsRoute: typeof AuthenticatedHouseholdsHouseholdIdSettingsRoute
  AuthenticatedHouseholdsHouseholdIdIndexRoute: typeof AuthenticatedHouseholdsHouseholdIdIndexRoute
}

const AuthenticatedHouseholdsHouseholdIdRouteChildren: AuthenticatedHouseholdsHouseholdIdRouteChildren =
  {
    AuthenticatedHouseholdsHouseholdIdListsRoute:
      AuthenticatedHouseholdsHouseholdIdListsRouteWithChildren,
    AuthenticatedHouseholdsHouseholdIdRecipesRoute:
      AuthenticatedHouseholdsHouseholdIdRecipesRouteWithChildren,
    AuthenticatedHouseholdsHouseholdIdSettingsRoute:
      AuthenticatedHouseholdsHouseholdIdSettingsRoute,
    AuthenticatedHouseholdsHouseholdIdIndexRoute:
      AuthenticatedHouseholdsHouseholdIdIndexRoute,
  }

const AuthenticatedHouseholdsHouseholdIdRouteWithChildren =
  AuthenticatedHouseholdsHouseholdIdRoute._addFileChildren(
    AuthenticatedHouseholdsHouseholdIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedHouseholdsHouseholdIdRoute: typeof AuthenticatedHouseholdsHouseholdIdRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedHouseholdsHouseholdIdRoute:
    AuthenticatedHouseholdsHouseholdIdRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
