// @generated drizzle-zero signature:sha256:2204ad9780a20eb2418c93489a147974892843695d144f16ac33d544516eb00f
// This file was automatically generated by drizzle-zero.
// You should NOT make any changes in this file as it will be overwritten.

import type { Row } from "@rocicorp/zero";
import { createBuilder } from "@rocicorp/zero";

const householdMembersTable = {
  name: "householdMembers",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    householdId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "household_id",
    },
    userId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "user_id",
    },
    role: {
      type: "string",
      optional: false,
      customType: null as unknown as "owner" | "member",
    },
    createdAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
  },
  primaryKey: ["id"],
  serverName: "household_members",
} as const;
const householdsTable = {
  name: "households",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    name: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    createdAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
  },
  primaryKey: ["id"],
} as const;
const recipeCookLogsTable = {
  name: "recipeCookLogs",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    householdId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "household_id",
    },
    recipeId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "recipe_id",
    },
    cookedAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "cooked_at",
    },
    comment: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    createdAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
  },
  primaryKey: ["id"],
  serverName: "recipe_cook_logs",
} as const;
const recipeIngredientsTable = {
  name: "recipeIngredients",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    householdId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "household_id",
    },
    recipeId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "recipe_id",
    },
    name: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    quantity: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    unit: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    note: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    position: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
    },
    createdAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
  },
  primaryKey: ["id"],
  serverName: "recipe_ingredients",
} as const;
const recipesTable = {
  name: "recipes",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    householdId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "household_id",
    },
    title: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    description: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    createdAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
  },
  primaryKey: ["id"],
} as const;
const shoppingItemsTable = {
  name: "shoppingItems",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    householdId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "household_id",
    },
    name: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    normalizedName: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "normalized_name",
    },
    status: {
      type: "string",
      optional: true,
      customType: null as unknown as "active" | "crossed" | "archived",
    },
    createdAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
  },
  primaryKey: ["id"],
  serverName: "shopping_items",
} as const;
const householdMembersRelationships = {
  household: [
    {
      sourceField: ["householdId"],
      destField: ["id"],
      destSchema: "households",
      cardinality: "one",
    },
  ],
} as const;
const householdsRelationships = {
  members: [
    {
      sourceField: ["id"],
      destField: ["householdId"],
      destSchema: "householdMembers",
      cardinality: "many",
    },
  ],
  recipes: [
    {
      sourceField: ["id"],
      destField: ["householdId"],
      destSchema: "recipes",
      cardinality: "many",
    },
  ],
  shoppingItems: [
    {
      sourceField: ["id"],
      destField: ["householdId"],
      destSchema: "shoppingItems",
      cardinality: "many",
    },
  ],
} as const;
const recipeCookLogsRelationships = {
  household: [
    {
      sourceField: ["householdId"],
      destField: ["id"],
      destSchema: "households",
      cardinality: "one",
    },
  ],
  recipe: [
    {
      sourceField: ["householdId", "recipeId"],
      destField: ["householdId", "id"],
      destSchema: "recipes",
      cardinality: "one",
    },
  ],
} as const;
const recipeIngredientsRelationships = {
  household: [
    {
      sourceField: ["householdId"],
      destField: ["id"],
      destSchema: "households",
      cardinality: "one",
    },
  ],
  recipe: [
    {
      sourceField: ["householdId", "recipeId"],
      destField: ["householdId", "id"],
      destSchema: "recipes",
      cardinality: "one",
    },
  ],
} as const;
const recipesRelationships = {
  household: [
    {
      sourceField: ["householdId"],
      destField: ["id"],
      destSchema: "households",
      cardinality: "one",
    },
  ],
  ingredients: [
    {
      sourceField: ["householdId", "id"],
      destField: ["householdId", "recipeId"],
      destSchema: "recipeIngredients",
      cardinality: "many",
    },
  ],
  cookLogs: [
    {
      sourceField: ["householdId", "id"],
      destField: ["householdId", "recipeId"],
      destSchema: "recipeCookLogs",
      cardinality: "many",
    },
  ],
} as const;
const shoppingItemsRelationships = {
  household: [
    {
      sourceField: ["householdId"],
      destField: ["id"],
      destSchema: "households",
      cardinality: "one",
    },
  ],
} as const;
/**
 * The Zero schema object.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const schema = {
  tables: {
    householdMembers: householdMembersTable,
    households: householdsTable,
    recipeCookLogs: recipeCookLogsTable,
    recipeIngredients: recipeIngredientsTable,
    recipes: recipesTable,
    shoppingItems: shoppingItemsTable,
  },
  relationships: {
    householdMembers: householdMembersRelationships,
    households: householdsRelationships,
    recipeCookLogs: recipeCookLogsRelationships,
    recipeIngredients: recipeIngredientsRelationships,
    recipes: recipesRelationships,
    shoppingItems: shoppingItemsRelationships,
  },
  enableLegacyQueries: false,
  enableLegacyMutators: false,
} as const;

/**
 * Represents the Zero schema type.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Schema = typeof schema;
/**
 * Represents a row from the "householdMembers" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type HouseholdMember = Row<
  (typeof schema)["tables"]["householdMembers"]
>;
/**
 * Represents a row from the "households" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Household = Row<(typeof schema)["tables"]["households"]>;
/**
 * Represents a row from the "recipeCookLogs" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type RecipeCookLog = Row<(typeof schema)["tables"]["recipeCookLogs"]>;
/**
 * Represents a row from the "recipeIngredients" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type RecipeIngredient = Row<
  (typeof schema)["tables"]["recipeIngredients"]
>;
/**
 * Represents a row from the "recipes" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Recipe = Row<(typeof schema)["tables"]["recipes"]>;
/**
 * Represents a row from the "shoppingItems" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type ShoppingItem = Row<(typeof schema)["tables"]["shoppingItems"]>;

/**
 * Represents the ZQL query builder.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const zql = createBuilder(schema);
/**
 * Represents the Zero schema query builder.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const builder = zql;

/** Defines the default types for Zero */
declare module "@rocicorp/zero" {
  interface DefaultTypes {
    schema: Schema;
  }
}
