// @generated drizzle-zero signature:sha256:3b200afbf9b7df609bf1b77f151012c99d4781691f67055c16d3873b4723ce02
// This file was automatically generated by drizzle-zero.
// You should NOT make any changes in this file as it will be overwritten.

import type { Row } from "@rocicorp/zero";
import { createBuilder } from "@rocicorp/zero";

const householdMembersTable = {
  name: "householdMembers",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    householdId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "household_id",
    },
    userId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "user_id",
    },
    role: {
      type: "string",
      optional: false,
      customType: null as unknown as "owner" | "member",
    },
    sortKey: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "sort_key",
    },
    createdAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
  },
  primaryKey: ["id"],
  serverName: "household_members",
} as const;
const householdModuleSettingsTable = {
  name: "householdModuleSettings",
  columns: {
    householdId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "household_id",
    },
    moduleKey: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "module_key",
    },
    enabled: {
      type: "boolean",
      optional: false,
      customType: null as unknown as boolean,
    },
    createdAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
  },
  primaryKey: ["householdId", "moduleKey"],
  serverName: "household_module_settings",
} as const;
const householdsTable = {
  name: "households",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    name: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    deletedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "deleted_at",
    },
    createdAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
  },
  primaryKey: ["id"],
} as const;
const listItemsTable = {
  name: "listItems",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    householdId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "household_id",
    },
    listId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "list_id",
    },
    name: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    normalizedName: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "normalized_name",
    },
    status: {
      type: "string",
      optional: true,
      customType: null as unknown as "active" | "crossed" | "archived",
    },
    sortKey: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "sort_key",
    },
    createdAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
  },
  primaryKey: ["id"],
  serverName: "list_items",
} as const;
const listsTable = {
  name: "lists",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    householdId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "household_id",
    },
    name: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    normalizedName: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "normalized_name",
    },
    sortKey: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "sort_key",
    },
    deletedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "deleted_at",
    },
    createdAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
  },
  primaryKey: ["id"],
} as const;
const recipeCookLogsTable = {
  name: "recipeCookLogs",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    householdId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "household_id",
    },
    recipeId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "recipe_id",
    },
    cookedAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "cooked_at",
    },
    comment: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    createdAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
  },
  primaryKey: ["id"],
  serverName: "recipe_cook_logs",
} as const;
const recipeImagesTable = {
  name: "recipeImages",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    householdId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "household_id",
    },
    recipeId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "recipe_id",
    },
    cookLogId: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "cook_log_id",
    },
    contentType: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "content_type",
    },
    byteSize: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "byte_size",
    },
    position: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
    },
    confirmedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "confirmed_at",
    },
    width: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
    },
    height: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
    },
    createdAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
  },
  primaryKey: ["id"],
  serverName: "recipe_images",
} as const;
const recipeIngredientsTable = {
  name: "recipeIngredients",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    householdId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "household_id",
    },
    recipeId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "recipe_id",
    },
    name: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    amount: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    note: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    position: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
    },
    createdAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
  },
  primaryKey: ["id"],
  serverName: "recipe_ingredients",
} as const;
const recipesTable = {
  name: "recipes",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    householdId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "household_id",
    },
    title: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    description: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    sortKey: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "sort_key",
    },
    deletedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "deleted_at",
    },
    createdAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
  },
  primaryKey: ["id"],
} as const;
const usersTable = {
  name: "users",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    username: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
  },
  primaryKey: ["id"],
} as const;
const householdMembersRelationships = {
  household: [
    {
      sourceField: ["householdId"],
      destField: ["id"],
      destSchema: "households",
      cardinality: "one",
    },
  ],
  user: [
    {
      sourceField: ["userId"],
      destField: ["id"],
      destSchema: "users",
      cardinality: "one",
    },
  ],
} as const;
const householdModuleSettingsRelationships = {
  household: [
    {
      sourceField: ["householdId"],
      destField: ["id"],
      destSchema: "households",
      cardinality: "one",
    },
  ],
} as const;
const householdsRelationships = {
  images: [
    {
      sourceField: ["id"],
      destField: ["householdId"],
      destSchema: "recipeImages",
      cardinality: "many",
    },
  ],
  listItems: [
    {
      sourceField: ["id"],
      destField: ["householdId"],
      destSchema: "listItems",
      cardinality: "many",
    },
  ],
  lists: [
    {
      sourceField: ["id"],
      destField: ["householdId"],
      destSchema: "lists",
      cardinality: "many",
    },
  ],
  members: [
    {
      sourceField: ["id"],
      destField: ["householdId"],
      destSchema: "householdMembers",
      cardinality: "many",
    },
  ],
  moduleSettings: [
    {
      sourceField: ["id"],
      destField: ["householdId"],
      destSchema: "householdModuleSettings",
      cardinality: "many",
    },
  ],
  recipes: [
    {
      sourceField: ["id"],
      destField: ["householdId"],
      destSchema: "recipes",
      cardinality: "many",
    },
  ],
} as const;
const listItemsRelationships = {
  household: [
    {
      sourceField: ["householdId"],
      destField: ["id"],
      destSchema: "households",
      cardinality: "one",
    },
  ],
  list: [
    {
      sourceField: ["householdId", "listId"],
      destField: ["householdId", "id"],
      destSchema: "lists",
      cardinality: "one",
    },
  ],
} as const;
const listsRelationships = {
  household: [
    {
      sourceField: ["householdId"],
      destField: ["id"],
      destSchema: "households",
      cardinality: "one",
    },
  ],
  items: [
    {
      sourceField: ["householdId", "id"],
      destField: ["householdId", "listId"],
      destSchema: "listItems",
      cardinality: "many",
    },
  ],
} as const;
const recipeCookLogsRelationships = {
  household: [
    {
      sourceField: ["householdId"],
      destField: ["id"],
      destSchema: "households",
      cardinality: "one",
    },
  ],
  recipe: [
    {
      sourceField: ["householdId", "recipeId"],
      destField: ["householdId", "id"],
      destSchema: "recipes",
      cardinality: "one",
    },
  ],
  images: [
    {
      sourceField: ["householdId", "recipeId", "id"],
      destField: ["householdId", "recipeId", "cookLogId"],
      destSchema: "recipeImages",
      cardinality: "many",
    },
  ],
} as const;
const recipeImagesRelationships = {
  household: [
    {
      sourceField: ["householdId"],
      destField: ["id"],
      destSchema: "households",
      cardinality: "one",
    },
  ],
  recipe: [
    {
      sourceField: ["householdId", "recipeId"],
      destField: ["householdId", "id"],
      destSchema: "recipes",
      cardinality: "one",
    },
  ],
  cookLog: [
    {
      sourceField: ["householdId", "recipeId", "cookLogId"],
      destField: ["householdId", "recipeId", "id"],
      destSchema: "recipeCookLogs",
      cardinality: "one",
    },
  ],
} as const;
const recipeIngredientsRelationships = {
  household: [
    {
      sourceField: ["householdId"],
      destField: ["id"],
      destSchema: "households",
      cardinality: "one",
    },
  ],
  recipe: [
    {
      sourceField: ["householdId", "recipeId"],
      destField: ["householdId", "id"],
      destSchema: "recipes",
      cardinality: "one",
    },
  ],
} as const;
const recipesRelationships = {
  household: [
    {
      sourceField: ["householdId"],
      destField: ["id"],
      destSchema: "households",
      cardinality: "one",
    },
  ],
  ingredients: [
    {
      sourceField: ["householdId", "id"],
      destField: ["householdId", "recipeId"],
      destSchema: "recipeIngredients",
      cardinality: "many",
    },
  ],
  cookLogs: [
    {
      sourceField: ["householdId", "id"],
      destField: ["householdId", "recipeId"],
      destSchema: "recipeCookLogs",
      cardinality: "many",
    },
  ],
  images: [
    {
      sourceField: ["householdId", "id"],
      destField: ["householdId", "recipeId"],
      destSchema: "recipeImages",
      cardinality: "many",
    },
  ],
} as const;
const usersRelationships = {
  householdMemberships: [
    {
      sourceField: ["id"],
      destField: ["userId"],
      destSchema: "householdMembers",
      cardinality: "many",
    },
  ],
} as const;
/**
 * The Zero schema object.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const schema = {
  tables: {
    householdMembers: householdMembersTable,
    householdModuleSettings: householdModuleSettingsTable,
    households: householdsTable,
    listItems: listItemsTable,
    lists: listsTable,
    recipeCookLogs: recipeCookLogsTable,
    recipeImages: recipeImagesTable,
    recipeIngredients: recipeIngredientsTable,
    recipes: recipesTable,
    users: usersTable,
  },
  relationships: {
    householdMembers: householdMembersRelationships,
    householdModuleSettings: householdModuleSettingsRelationships,
    households: householdsRelationships,
    listItems: listItemsRelationships,
    lists: listsRelationships,
    recipeCookLogs: recipeCookLogsRelationships,
    recipeImages: recipeImagesRelationships,
    recipeIngredients: recipeIngredientsRelationships,
    recipes: recipesRelationships,
    users: usersRelationships,
  },
  enableLegacyQueries: false,
  enableLegacyMutators: false,
} as const;

/**
 * Represents the Zero schema type.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Schema = typeof schema;
/**
 * Represents a row from the "householdMembers" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type HouseholdMember = Row<
  (typeof schema)["tables"]["householdMembers"]
>;
/**
 * Represents a row from the "householdModuleSettings" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type HouseholdModuleSetting = Row<
  (typeof schema)["tables"]["householdModuleSettings"]
>;
/**
 * Represents a row from the "households" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Household = Row<(typeof schema)["tables"]["households"]>;
/**
 * Represents a row from the "listItems" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type ListItem = Row<(typeof schema)["tables"]["listItems"]>;
/**
 * Represents a row from the "lists" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type List = Row<(typeof schema)["tables"]["lists"]>;
/**
 * Represents a row from the "recipeCookLogs" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type RecipeCookLog = Row<(typeof schema)["tables"]["recipeCookLogs"]>;
/**
 * Represents a row from the "recipeImages" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type RecipeImage = Row<(typeof schema)["tables"]["recipeImages"]>;
/**
 * Represents a row from the "recipeIngredients" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type RecipeIngredient = Row<
  (typeof schema)["tables"]["recipeIngredients"]
>;
/**
 * Represents a row from the "recipes" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Recipe = Row<(typeof schema)["tables"]["recipes"]>;
/**
 * Represents a row from the "users" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type User = Row<(typeof schema)["tables"]["users"]>;

/**
 * Represents the ZQL query builder.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const zql = createBuilder(schema);
/**
 * Represents the Zero schema query builder.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const builder = zql;

/** Defines the default types for Zero */
declare module "@rocicorp/zero" {
  interface DefaultTypes {
    schema: Schema;
  }
}
